PRAGMA foreign_keys = ON;

INSERT OR REPLACE INTO companies (
  edinet_code, sec_code, filer_name, listed_category, industry
) VALUES (
  'E00000', '9999', 'サンプル株式会社', '上場', '情報・通信業'
);

INSERT OR REPLACE INTO documents (
  doc_id, edinet_code, sec_code, doc_type, ordinance_code, form_code, doc_type_code,
  period_start, period_end, submit_date_time, withdrawal_status, doc_description, source_meta_json
) VALUES (
  'SAMPLE-DOC-2025', 'E00000', '9999', 'annual',
  '010', '030000', '120', '2024-04-01', '2025-03-31',
  '2025-06-28T09:00:00Z', '0', 'Sample annual securities report',
  '{"source":"local-d1-seed","note":"generated by infra/init/seed-local-d1.sql"}'
);

INSERT OR REPLACE INTO period_financials (
  edinet_code, sec_code, doc_id, doc_type, period_start, period_end, submit_date_time, filer_name,
  summary_json, pl_json, bs_json, cf_json, raw_tsv_path
) VALUES (
  'E00000', '9999', 'SAMPLE-DOC-2025', 'annual',
  '2024-04-01', '2025-03-31', '2025-06-28T09:00:00Z', 'サンプル株式会社',
  '{"revenue":1234567890,"operatingProfit":234567890,"netIncome":123456789}',
  '{"revenue":1234567890,"operatingProfit":234567890}',
  '{"totalAssets":3456789012,"equity":1567890123}',
  '{"operatingCF":210000000,"investingCF":-90000000,"financingCF":-50000000}',
  NULL
);

INSERT OR REPLACE INTO sec_code_latest_periods (
  sec_code, edinet_code, filer_name, latest_doc_id, latest_period_end, latest_submit_date_time
) VALUES (
  '9999', 'E00000', 'サンプル株式会社', 'SAMPLE-DOC-2025', '2025-03-31', '2025-06-28T09:00:00Z'
);

INSERT OR REPLACE INTO daily_metrics (
  snapshot_date, company_count, document_count, period_financial_count
) VALUES (
  '2025-06-28', 1, 1, 1
);
